# Generated by Django 3.1.2 on 2020-10-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newecom', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
