# Generated by Django 3.1.2 on 2020-10-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newecom', '0003_auto_20201021_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
